version: '3.8'
services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - ollama
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
    - ~/.ollama/:/root/.ollama

